# Generated by Django 4.2.2 on 2023-07-17 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_jobpost_type_alter_jobpost_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobpost',
            name='type',
            field=models.CharField(choices=[('Full Time', 'Full Time'), ('Part Time', 'Part Time')], max_length=200),
        ),
    ]
